FROM mcr.microsoft.com/dotnet/aspnet:6.0-bullseye-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0-bullseye-slim AS build
WORKDIR /src
COPY . .
RUN dotnet restore "Nacos2Demo.sln"
WORKDIR /src/NetCoreConfigDemo
RUN dotnet build "NetCoreConfigDemo.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "NetCoreConfigDemo.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV TZ=Asia/Shanghai
RUN sed -i 's/TLSv1.2/TLSv1.0/g' /etc/ssl/openssl.cnf
ENTRYPOINT ["dotnet", "NetCoreConfigDemo.dll"]
